language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
# command to install dependencies
install:
  - pip install codecov
  - pip install -r requirements.txt
# command to run tests
script:
  - coverage erase
  - coverage run --source=. -m pytest

after_success:
  - codecov